### ISSUE TITLE
While giving customized title , not able to change the size of title in index.js ,though we change it to the lowest size with h6 ,still my title size change is not reflecting .

### ISSUE THREAD

**Issue by Subhashini-1** [DannyDainton/newman-reporter-htmlextra#11]
While giving customized title , not able to change the size of title in index.js ,though we change it to the lowest size with h6 ,still my title size change is not reflecting .

![image](https://user-images.githubusercontent.com/44973580/53478009-e6eacc00-3a9b-11e9-93d4-73c929239e1b.png)
![image](https://user-images.githubusercontent.com/44973580/53478033-f0743400-3a9b-11e9-82ac-5dddf3d979c0.png)

**Comment by DannyDainton** [comment]
Hey @Subhashini-1 

Thank you for using the reporter - This seems like an issue with the custom template that you have created, rather than a specific issue with the reporter. 

I can advise what you could do in your report but this isn't something that I need to change in the reporter. I can look at changing the sizing in the default template, to allow for longer titles but you can do this in your own template.

**Comment by DannyDainton** [comment]
Closing this issue, happy to reopen if you feel it doesn't answer the queston.

**Comment by Subhashini-1** [comment]
Thanks Danny for the inputs .I have modified it and its working as needed !
