### ISSUE TITLE
Email sending 

### ISSUE THREAD

**Issue by Subhashini-1** [DannyDainton/newman-reporter-htmlextra#12]
Hi @DannyDainton 

This is not an issue .Need your inputs if you can help me with email triggering of report generated with newman integration .Is there any plugin or helpers which would serve this need.

**Comment by DannyDainton** [comment]
I would look into creating a node script and incorporate this functionality there. There will plenty of modules that could give you some help with this.

I'm closing this as it's not an issue with the reporter.

**Comment by kajol1701** [comment]
Hi @DannyDainton
I used the code you provided above. And sent the report as an attachment. The mail is triggered and the user gets it too. But when I open it from the mail itself without downloading it, it appears in a non-formatted way. But when I download it and open the file it opens up properly. Just wanted to know why is this happening. Because of some Gmail default settings like the Jenkins have? 
`   newman
      .run({
        collection: require("../../../../c.json"),
        environment: require("../../../../e.json"),
        reporters: ["htmlextra"],
        reporter: {
          htmlextra: {
            export:
              "/home/kajol/Workspace/basis-server/public/templates/TestReport.html"
          }
        }
      })
      .on("start", function(err, args) {
        // on start of run, log to console
        console.log("running a collection...");
      })
      .on("done", function(err, summary) {
        if (err || summary.error) {
          console.error("collection run encountered an error.");
        } else {
          console.log("collection run completed.");

          sendEmail(["example@gmail.com"], "Test Report", "Hi", true, [
            {
              path: `/templates/TestReport.html`
            }
          ]);
        }
      });`

**Comment by DannyDainton** [comment]
Hey @kajol1701

Thanks for posting your question here, it's easier to manage than via email 😁

So the report templete's styling is coming from CDNs to specific resources rather than the code being embedded in the template itself. The report is already huge under certain circumstances (very large collections and multiple x1000 iterations) and adding that in they would increase the final report size too.

I think that also Gmail blocks external CDNs, I don't know this for sure but I was having a look and searching for some information.

Found this reply on SO - seems to be security related and makes sense why:

https://stackoverflow.com/a/56910981/6028443

**Comment by kajol1701** [comment]
Thanks for replying:smile: I get it now.

**Comment by DannyDainton** [comment]
No worries, it's a shame that it doesn't work in the way that you hoped but that seems to be on the email client rather than the reporter. 😔

Sounds like sending as an attachment seems to work, after downloading it, so at least there's a workaround 😁

**Comment by kajol1701** [comment]
Yep, sending as an attachment did work and after downloading the file opened perfectly. And please don't say that. Newman is overall the best thing I came across, has helped me and my organization int the best manner to get to know the API issues with proper mentioning of everything in the report. 
Again, Thanks a lot! You are too kind to help me out. Also, will be worrying you again as using Newman a lot for my work!

**Comment by kajol1701** [comment]
Hi @DannyDainton 
Is there a way to automatically download the collection from the postman? Actually downloading the collection every time to generate the report is a bit tedious.

**Comment by DannyDainton** [comment]
Are you exporting it as a JSON file each time?

You can use either the Collections sharable Public link or the most up to date version of the collection using the Postman API - Both of these can be used in the newman run command.
