### ISSUE TITLE
How to provide descriptive name for an iteration

### ISSUE THREAD

**Issue by sup-engineer** [DannyDainton/newman-reporter-htmlextra#136]
First of all , thanks for this lovely reporter!

I am running my collection against a set of test vectors. I would like to add some form of test vector reference string along with the iteration number in the final report as shown below:
![image](https://user-images.githubusercontent.com/20064961/63533852-8e096700-c505-11e9-9ff2-114e0c9ac90f.png)

This test vector reference string will change for each iteration of the run (let's say it's picked up from the data file.csv)

Can I achieve this? if so how?

I started looking into custom templates . I am struggling to see how I would pickup this information from the data file .csv (which will be available in each iteration in postman) within the context of html reporter.

**Comment by DannyDainton** [comment]
Hey @sup-engineer,

Appreciate the kind words!! 🏆

Umm...it's just a string that happens to be a number so it _could_ be something that works for you but I don't know how you would feed it that data from a collection.

I don't really like the way I've added the tabs and I haven't had time to change it, once you have like 22+ iterations, it starts to truncate and look ugly. Adding text to that would reduce that amount and it will end up looking a bit crap.

Let me have a think about this and get back to you.

**Comment by sup-engineer** [comment]
yes..I agree....the default template is probably enough for most users. So i am not sure if it is worth modifying your default template to achieve this...so I am thinking of modifying your default hbs and creating a custom template for this. 

I am stuck with a couple of things. hoping you can help point me in the right direction.

The reason I thought we could access information from the 'data' object is because of the last section on this page:

https://learning.getpostman.com/docs/postman/scripts/postman_sandbox/  

![image](https://user-images.githubusercontent.com/20064961/63593405-d713f680-c5ab-11e9-8d1b-ea896b261341.png)

1. Does this mean it can somehow be accessed {{summary.<something>.data.<required value>}} in the hbs? --> this is the bit I don't understand

2. Also I can see where the iteration tabs get the content string from . i.e the html list items  
![image](https://user-images.githubusercontent.com/20064961/63593846-c912a580-c5ac-11e9-9c82-3fee2e813ccb.png)

But, I can't seem to find where this is defined in the hbs. I could identify the html unordered list defined in line 381 of the default template, but don't understand how/where the individual list items of this list are defined:
![image](https://user-images.githubusercontent.com/20064961/63594001-332b4a80-c5ad-11e9-91ff-014cd7304b10.png)

**Comment by DannyDainton** [comment]
For point 1 - No it doesn't work like that, unfortunately. It would make things easy if it did :) That data file is accessed via a Postman Collection using `pm.iterationData.get('var_name')` or using the `{{var_name}}` syntax in specific places in the UI. Newman doesn't actually expose that data which is doesn't help when you even what to display something simple like the name of the data file being used for the run.

I wrote this last year so _try_ about explain how the data gets to a handlebars template - https://dannydainton.com/2019/02/10/dont-let-go-of-the-handlebars/

For point 2 - The script that does that and dynamically creates the tabs is at the bottom of the template if you do a find on `iteration-` you should see it. The part that you highlight just tells it where to display that on the page. It's pretty hacky, I don't like the way it's done but it's something different to the standard HTML reporter.

**Comment by sup-engineer** [comment]
@DannyDainton  thank you. I went through that post.

I am now looking to use the environment variables to achieve this instead of iterationData. I was hoping if you could clarify one doubt I have.

when I use {{#with summary}}, is this summary object not the same as the one returned from the newman.run ~callback as shown below??:
![image](https://user-images.githubusercontent.com/20064961/63872311-732b6c80-c9b5-11e9-9f81-811204df69a6.png)

When I run the following JavaScript code, I can successfully print the value of my testcaseName environment variable to console:
![image](https://user-images.githubusercontent.com/20064961/63872648-f947b300-c9b5-11e9-95c9-6c7a32f8102d.png)

However, when I modify your hbs template as shown below, I do not seem to be able to access the value of this environment variable (I have marked the lines I have changed):
![image](https://user-images.githubusercontent.com/20064961/63872817-55123c00-c9b6-11e9-85ea-906c5b975773.png)

The li items for different iterations are not created in the final report.

if I directly assign a string to the testcase variable, then then it seems to work. 

I can't seem to figure out why I cannot access the same data from the hbs template. What am I missing?

**Comment by DannyDainton** [comment]
Awesome work so far - Really glad you're giving it a go!!

So the reporter uses the data from the `beforeDone` event, give or take a few tweeks, so that structure of that data would be different from the summary data you see. I think that's using the `done` event. 

If you take a look at the `index.js` file for the reporter, you will be able to see where it's getting the data from and hopefully workout what's happening in relation to the handlebars syntax.

**Comment by DannyDainton** [comment]
Hey,

I'm going to close out this issue as it's not something that's specifically _wrong_ with the reporter itself, it's something that you would like to achieve for your use case.

 I'm happy to continue discussing the issue off line with you though.

**Comment by sup-engineer** [comment]
Hey @DannyDainton  no worries. Yes, there is nothing specifically wrong with the reporter. Also thanks for pointing me to the correct place to look in the index.js . I noticed that the collection environment is already exported from index.js and can be accessed in the handlebars template.

I have managed to customise the template to get a solution for my use case. Here is what I did in case anyone else is interested in doing the same:

Step 1: create an environment variable which will be used to hold the testcase name string from each iteration. Append the testcase name string to this variable in each iteration with some pre-defined delimiter . In my case I have used the '!' character as delimiter and am doing it as part of pre-request script in first step of my postman collection. Also as can be seen, I am getting the testcase name string for each iteration from my data file
![image](https://user-images.githubusercontent.com/20064961/64964793-aca81700-d893-11e9-871f-758ca6d9362b.png)

Step 2: Modified the default handlebars template to add a few lines to read the environment variable and extract the testcase name for each iteration and append it to the suitable place (in my case to the iteration list item):
![image](https://user-images.githubusercontent.com/20064961/64965288-a23a4d00-d894-11e9-8355-43c496cae712.png)

Result : this is how my test result looks
![image](https://user-images.githubusercontent.com/20064961/64965879-ae72da00-d895-11e9-82a9-27e2ae0f384b.png)

**Comment by marenchen** [comment]
@sup-engineer @DannyDainton Where can I find the handlebars file that was edited here?

**Comment by shreyasrastogi** [comment]
@DannyDainton @sup-engineer ,
i did the above solution , but cannot access the environment variable inside handlebar place where this code was mentioned ,
is there any other way to access env variable 

let teststring = "{{environment.name}}";

  for(var i = 0; i < totalIterations; i++)
  {
    let li = document.createElement('li');
    li.appendChild(document.createTextNode((i + 1 + teststring)));
    li.setAttribute('id', 'iteration-' + i);
    li.classList.add("custom-tab");
    li.classList.add("itPassed");

**Comment by DannyDainton** [comment]
To access the environment variable in the way that @sup-engineer is you would need to reference it correctly.

You would also need to ensure that you're using the full handlebar syntax to get access to the data in the collection.

Take a look at the image and see what you have and what's missing.

This is not my solution of something that I've tried in the reporter so I can only offer some pointers.

**Comment by shreyasrastogi** [comment]
@DannyDainton  , this approach does not work for me , i was able to get the data in a env variable to the hbs template , if i replace the environment.name at top with environment.values.reference.testcaseName.value i see the value , but inside javascript it does not get the value , not sure what i am missing here

**Comment by DannyDainton** [comment]
Only you can see what you're trying to explain - without seeing that code, I don't know what you're talking about. 😂

**Comment by shreyasrastogi** [comment]
Hi @DannyDainton  
In Dashboard template  at line 527 i see environment.name and its value is present 
![image](https://user-images.githubusercontent.com/43715277/115790592-f07ad080-a394-11eb-869d-103b95d9452a.png)
i am trying to access the same environment.name inside javascript , so  not able to get the value , I might be doing it in a wrong manner if you can point out the issue that will be of help 

![image](https://user-images.githubusercontent.com/43715277/115790810-4e0f1d00-a395-11eb-984f-df385e54c026.png)

Thanks.

**Comment by DannyDainton** [comment]
Take a look at the way that's referenced in the first image and then look how it's referenced in the second.

`{{environment.name}}` doesn't mean anything on it's own as it comes under `{{#with summary}}`

You're best off getting a basic understanding of where and how the different pieces of data in the report actually get there first, then look at this specific task.

Here's something I wrote ages ago:

https://dannydainton.com/2019/02/10/dont-let-go-of-the-handlebars/

**Comment by shreyasrastogi** [comment]
Hi @DannyDainton  thanks for pointing me out to the last article . it was a issue of scope , it works now with below code segment 

  {{#with summary}}
    let teststring = "{{environment.values.reference.testCaseName.value}}";
    let testCaseArray = teststring.split("!");
  {{/with}}

Thanks

**Comment by wiczit** [comment]
Dears, finally I've made it to repeat this solution at my site. kudos @sup-engineer 
Because I am not really familiar with recent front end developments I am having a question.
As @DannyDainton ve said, the select iteration box is too short for descriptive labels (marked red), but once the iteration "is selected" there is a label that would have space for the info. (marked green)
![image](https://user-images.githubusercontent.com/15891031/123638954-05a22e80-d820-11eb-81db-341e62f036fc.png)

My question: How to populate this "xxx selected" label with the descriptive label only and how to add there further labels with info from the test environment export?

![image](https://user-images.githubusercontent.com/15891031/123639806-d5a75b00-d820-11eb-98e5-e8c262f0ca66.png)

**Comment by mokolad** [comment]
Hello everyone! Thank you @DannyDainton for your help on this thread even though it's a couple of years old.

@sup-engineer and @wiczit - I've been trying to do the same as you, but I'm facing a couple of problems.

First: I made the pre-request script by following the steps and when running the collection through Postman, I can see all the test cases names collecting in the "Current value" of the environment variable and I can print it to the console. But when running it through newman, it just prints "undefined,undefined,undefined..." - I think it's unable to access the "Current value" of the variable and because of that the iteration names in the generated HTML report are just "1 - ", "2 - ", etc. 
`var currentTestString = pm.environment.get("testCaseName") + data.Test_case_info + ","; `
`pm.environment.set("testCaseName", currentTestString);`

This is how I run it:
`call newman run %postman_collection% -e %postman_environment% -d %postman_data% --folder %postman_folder% -r cli,htmlextra --reporter-htmlextra-browserTitle "<FOLDER NAME>" --reporter-htmlextra-Title "<COLLECTION NAME>: <FOLDER NAME>" --reporter-htmlextra-titleSize 4 --reporter-htmlextra-export "%reports_folder%\FOLDERNAME.html" 
`

Second: At first I thought I had referenced the value incorrectly in the handlebars file, so I tried referencing another value which does not change, like the Base Url which is part of the environment JSON, so I wrote `let testCaseName = "{{environment.values.reference.BASE_URL.value}}"`, but I didn't get the value. I know the path is correct, because when I place it somewhere else in the file, for example in place of `Environment: {{environment.name}}`, the URL shows up as the Environment name in the report. So for some reason I'm not able to reference the values of the variables with `"{{environment.values.reference.ENVVAR.value}}"` and I'm not sure why.

Unfortunately due to network policy, I'm not able to upload and share screenshots, so I hope I was able to explain it. Does anyone have any idea about this? I would be very happy if anyone could help, since we run the same set of chained request with data from a CSV file and it would be very useful to be able to name the iterations so it's clear which scenario has passed/failed, etc. Thank you! 🙏

**Comment by wiczit** [comment]
Hi @mokolad, great to see you joining the topic.
As a quick response for _it just prints "undefined,undefined,undefined..."_
..you may try to export the environmental variables and check the values inside ..
`newman run collectionPreReq.json -e Environment.json -k --export-environment newmanExport.json`

`
.custom-tab {
  padding: 10px 15px;
  margin-right: 0px;
  /*height: 47px;*/
  /*width: 69px;*/
  text-align: left;
  border: var(--tab-border);
  border-bottom: none;
  cursor:pointer;
  display: block;
  width: 100%;
}`

`.single-line-tabs {
  padding-top: 10px;
  height: 250px;
}`

Best M

**Comment by DannyDainton** [comment]
Any data in the `Current Value` isn't synced or exported from the app, as that's just your own sessions that aren't shared. The values would need to also be in the `Initial Value` section before exporting.

**Comment by mokolad** [comment]
Thanks for your comments! I did the export and inside I see
`{
      "type": "any",
      "value": "undefined,undefined,undefined,undefined,undefined,undefined,undefined,",
      "key": "testCaseName"
    }`

However, other environment variables without Initial Values are exported with their Current Value. For example, I use moment in my pre-request to create a date like `pm.environment.set("shortDate", moment().format("YYYY-MM-DD"));` and this variable is exported after the run
`{
      "type": "any",
      "value": "2021-07-06",
      "key": "shortDate"
    }`

Also, other variables whose values are set based on the previous request's response are also exported with their Current Values. It seems like it can't "read" the value from the CSV file and assign it to the variable (I have no problems with the rest of the cells in the CSV, the request body is populated correctly).

**Comment by DannyDainton** [comment]
What script are you using to get the data from the file and then have that stored in the environment file?

**Comment by mokolad** [comment]
Hi Danny, thank you for helping!

 `data.Test_case_info` references column A in my CSV file where I've written the different test case names for each iteration. I've copied @sup-engineer's prerequest script
`var currentTestString = pm.environment.get("testCaseName") + data.Test_case_info + ",";`
`pm.environment.set("testCaseName", currentTestString);`

and I've also added a couple of console logs just to see what's happening:
`console.log(data.Test_case_info);`
`console.log(pm.environment.get("testCaseName"));`

and I run it with a .bat file:

> SET postman_collection=%cd%\COLLECTION.json
> SET postman_environment=%cd%\ENVIRONMENT.json
> 
> SET postman_folder="FOLDER"
> SET postman_data="%cd%\TestData_CSV\TestData.csv"
> SET reports_folder=%cd%\NewmanReports\
> 
> call newman run %postman_collection% -e %postman_environment% -d %postman_data% --folder %postman_folder% -r cli,htmlextra --reporter-htmlextra-browserTitle "FOLDER NAME" --reporter-htmlextra-Title "COLLECTION NAME: FOLDER NAME" --reporter-htmlextra-titleSize 4 --reporter-htmlextra-export "%reports_folder%\FOLDERNAME.html"

Running through Postman Runner with the CSV file prints the current iteration test case (column A from the CSV) and also the accumulated value of `testCaseName` in the console. 

> 11:49:51.016
> "Test_Case_4_Name"
>  
> 11:49:51.017
> "Test_Case_1_Name,Test_Case_2_Name,Test_Case_3_Name,Test_Case_4_Name,"

However when I run it using the .bat file, it prints:

>   │ null
>   │ 'undefined,undefined,undefined,undefined,undefined,undefined,'

**Comment by DannyDainton** [comment]
Personally, I've never liked `data.Test_case_info` as it's the older way of reading the data from a file. 

Would using `pm.iterationData.get('Test_case_info')` help here.

Also, Postman and Newman are 2 different projects and are not 100% aligned with the way that they both work. There are different things that happen in the app code that won't work when running the Collection with Newman. Just something the to cautious of when debugging something through the app and then getting a different result when run with Newman.

**Comment by mokolad** [comment]
Thanks for pointing this out, I'll make sure to remember it and use the proper way to read data from file!

I updated the way the data is read, but after running the file I still saw 'null' and 'undefined'. I decided to try printing another value from another column in the CSV, just to see if the issue was with the name of the column or any of the values, and it did work. So after some trial and error I discovered that it was not "seeing" the first column in the CSV. I moved the test case names as the last column in the CSV and they are now being printed correctly and the `testCaseName` variable is also printed and is a part of the exported environment after the run. Thanks for helping me with this, Danny! 🙏

> │ 'Test_Case_4_Name'
> │ 'Test_Case_1_Name,Test_Case_2_Name,Test_Case_3_Name,Test_Case_4_Name,'

I still have the issue with the .hbs file, though :( I've made it according to the previously shared screenshots:

```
>   {{#with summary}} {{#with stats}}
>   let totalIterations = {{iterations.total}};
>   let testCaseString = "{{environment.values.reference.testCaseName.value}}";
>   let testCaseArray = testCaseString.split(",");
> 
>   let menu = document.querySelector('#execution-menu .nav');
> 
>   for(var i = 0; i < totalIterations; i++)
>   {
>     let li = document.createElement('li');
>     li.appendChild(document.createTextNode((i + 1) + " - " + testCaseArray[i+1]));
```

but when the HTML file is generated, the iterations are named "1 - UNDEFINED", "2 - UNDEFINED", etc. I also tried again to substitute the `testCaseName` variable with my `BASE_URL` variable, which has a constant "Initial value" and is a part of the env json, but it seems like it's not able to access any of my environment variables. This time, I'm not sure what I'm doing wrong since I'm not very familiar with handlebars 😞

**Comment by DannyDainton** [comment]
Those items wouldn't be in `{{#with stats}}` that seems like a lower level. Can you remove that block and see if that helps?

**Comment by mokolad** [comment]
Thanks for the example! I removed the {{#with stats}} block and it removed the iterations`<li>` from the report, it just groups all request from all iterations together in a big list without the separate tabs you can click through to view each individual iteration. So I made it like this:

```
{{#with summary}} {{#with stats}}
  let totalIterations = {{iterations.total}};
  {{/with}}
  let testCaseString = "{{environment.values.reference.testCaseName.value}}";
  let testCaseArray = testCaseString.split(",");
  

  let menu = document.querySelector('#execution-menu .nav');

  for(var i = 0; i < totalIterations; i++)
  {
    let li = document.createElement('li');
    li.appendChild(document.createTextNode((i + 1) + " - " + testCaseArray[i+1]));
    ...
  }
{{/with}}  
```

and now the iterations are named! Thank you so much for your help! I hope this is useful for anyone who wants to achieve the same.

**Comment by matifniaz** [comment]
@DannyDainton @sup-engineer @mokolad 
Please help to solve above problem.
Pre-Request Script - Collection Level:
![image](https://user-images.githubusercontent.com/40147842/154792483-66c7a7c0-ab8a-4bc2-b5f8-19153bc46f85.png)
CSV File:
![image](https://user-images.githubusercontent.com/40147842/154792507-76b0c3c3-c6e3-49e9-94bc-999d940d9bbe.png)
Template file:
![image](https://user-images.githubusercontent.com/40147842/154792555-3e45cd57-6485-40fe-897d-6f5fa92b98f7.png)
Generated Report:
![image](https://user-images.githubusercontent.com/40147842/154792602-8ba97789-206a-4cc6-a7e6-52265086823c.png)

**Comment by DannyDainton** [comment]
That's not my solution but I'm wondering why you have commentted out the `{{#with stats}} {{/with}}` blocks in that image?

`{{iterations.total}}` is in `stats` so that variable wouldn't be showing the correct value.

**Comment by matifniaz** [comment]
@DannyDainton - thanks for quick response.
When I enable in template
![image](https://user-images.githubusercontent.com/40147842/154793797-a7377875-cbcf-41bf-9e1b-3e939c03c516.png)
Then following error occur and report not generated.
![image](https://user-images.githubusercontent.com/40147842/154793824-970706f7-e758-4378-b0b1-135412b6c3b1.png)
@DannyDainton Can you share your solution file with for reference. Thanks in advanced.

**Comment by DannyDainton** [comment]
I don't that what else is in that custom template to know where the error is coming from. You don't get a ton of information from cropped images. 

This isn't something that I've created or worked on, it's a custom template created by a user of the reporter. 

I'm not spending any time chasing errors that where no created by me 😂

Getting a better understanding of what the code is trying to do with the Newman Summary Object and how handlebars works will help you more here.
