### ISSUE TITLE
Final report name.

### ISSUE THREAD

**Issue by tonycantony0007** [DannyDainton/newman-reporter-htmlextra#14]
Hi Danny,
               This is not an issue .Needs your input so that by default the html report name should be the collection name followed by the date.If we are running a group of collection at same time,if this functionality is there it will be helpful to identify the specific collection report.(Without using exporter option while running.)

**Comment by DannyDainton** [comment]
Hey,

You could create a template or use the existing one and then change the `{{title}}` reference to be `{{collection.name}}` - depending on the length of this name, you might want to also change the `class="display-*"` number to reduce the size of the main title.

Is that what you had in mind?

**Comment by tonycantony0007** [comment]
Thanks Danny.. This is not i meant.when  we get a report after testing the file name will be in the format newman-run-report-htmlextra-2019-02-21-07--01-57-094-0  i want this report file name to be in the format "collection name -date".

**Comment by DannyDainton** [comment]
Ah ok - I understand what you mean now. An example of what you meant would have saved the confusion but it's all good now. :)

I've made a change to the reporter and published a new version that should hopefully give you what you need. As the collection name forms part of the default file name now, you will need to ensure the it's a valid filename path.

I'll leave this issue open until you have updated and given it a go. :)

**Comment by DannyDainton** [comment]
Going to close this Issue - Can reopen if this doesn't help with the problem you are facing.

**Comment by DannyDainton** [comment]
@tonycantony0007 Was this what you had in mind?

**Comment by JLaMarcaIDEXX** [comment]
Is there a way to disable the timestamp in the file name and have each collection overwrite the last run each time?

**Comment by DannyDainton** [comment]
Hey @JLaMarcaIDEXX 

By default, if you don't tell the reporter where to save the output file, it will create a new one each time (With a new timestamp) in the `newman` directory.

If you use the `--reporter-htmlextra-export ./newman/myReport.html` flag, it will _overwrite_ the report each time and save it with that filename.  You can obviously name that file whatever you like and point it to a better directory.

**Comment by JLaMarcaIDEXX** [comment]
excellent thank you!

**Comment by raygao** [comment]
--reporter-htmlextra-export ./newman/myReport.html flag does not work. It will create a new file with a new time-stamp each time the script is ran. It would be nice to be specify a file. So, I can automate some activities.

**Comment by raygao** [comment]
must have following format to save the file.
/usr/bin/newman run test.json -e environment.json --reporters cli,htmlextra --reporter-htmlextra-export results/output.html

**Comment by DannyDainton** [comment]
@raygao 

This doesn't really mean anything to anyone:
> --reporter-htmlextra-export ./newman/myReport.html flag does not work.

It more than likely didn't work because you didn't have a `/newman` directory created at that level for the file to be exported too. It would have fallen back to the default export location, which would be in the form of `collection_name_timestamp._0.html` in the newly created `/newman` directory, in the same place the command was executed. 

The `filename` and `path` value added to the `--reporter-htmlextra-export` flag, needs to be valid and an accessible directory, for the reporter to export the final report, else it will fallback to the default.

**Comment by cool-kostian** [comment]
Hey @DannyDainton 

Thanks for NEWMAN. My team is excited with it.

is there any way to have a custom unique name for each report without overwrite? for example:
`path/reporter/CUSTOM_NAME+{{timestamp}}.html"`

**Comment by DannyDainton** [comment]
Using the `--reporter-htmlextra-export` would allow you to call it whatever you like.

If you running it from a script it's going to be easier to add the desired name as the final exported report name. From the Command line, it's slightly trickier but not impossible.

What have you tried so far and what's not working?

**Comment by cool-kostian** [comment]
@DannyDainton  Thanks for the quick reply.

I'm using 'Newman' with 'htmlextra' reporter in Jenkins and my team want to have a custom name for reporting like: `--reporter-htmlextra-export "path/NAMEofCOLLECTION+Environmane+Timestamp.html"` with a purpose to easily navigate to the exact report (where the difference will be "Environment + Timestamp" only)

**Comment by DannyDainton** [comment]
Whatever you add there is completely controlled by you and doesn't really have anything to do with the reporter. That gives you the ability to add the name you want rather than the default name from the reporter. 

I'm sure that the name can include those things if you add them dynamic variables in the script you're running in Jenkins. You could create variables for the different elements of the command and then construct the filename using that. 

I honestly don't know Jenkins that well or know how you have your jobs set up to be able to help you with that part.
