### ISSUE TITLE
getting following error "newman: htmlextra reporter could not be loaded.   please install reporter using npm"

### ISSUE THREAD

**Issue by JamalMSaad** [DannyDainton/newman-reporter-htmlextra#145]
Hi ,
I installed newman using 'npm install -g newman' from the terminal,
and used newman commands to run my postman collections, and it is working fine and gives me the default report, but i wanted to create better HTML reports by installing html and htmlextra report using the following commands 'npm install -g newman-reporter-html' and 'npm install -g newman-reporter-htmlextra'

The result of 'npm install -g newman-reporter-html' is:
npm WARN newman-reporter-html@1.0.3 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

The result of 'npm install -g newman-reporter-htmlextra' is:
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN newman-reporter-htmlextra@1.8.8 requires a peer of newman@>=4 but none is installed. You must install peer dependencies yourself.
+ newman-reporter-htmlextra@1.8.8
added 229 packages from 472 contributors in 9.193s

+ newman-reporter-html@1.0.3

But when running the collection "newman run <My-Collection_Name>.json -r htmlextra" it gives me the following error :
"newman: "htmlextra" reporter could not be loaded. please install reporter using npm"

 - 'newman' Version [4.5.4]
 - 'newman-reporter-htmlextra' Package Version [1.8.8]
 - 'macOS Mojave' Version[ 10.14.6]
- 'Node' : v12.10.0
- 'NPM' : v6.9.0

Please find attached the collection that i am running.
[Newman-Collection.postman_collection.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/3591519/Newman-Collection.postman_collection.zip)

Thx in advance.

**Comment by DannyDainton** [comment]
Not really sure what's going on here, I would have to put this down to an environmental issue as if I were a global problem for everyone, we would have more reports of the same issue.

I hate to give you a kinda turn on and off again solution but could you do the following:

`npm uninstall -g newman newman-reporter-htmlextra`

and then do a full install again:

`npm install -g newman newman-reporter-htmlextra`

By doing this, at least you know that both packages are installed at the same level before running the command again.

**Comment by JamalMSaad** [comment]
both packages are installed at the same level but the issue still exists , check the following screen shot .
![Screen Shot 2019-09-10 at 10 51 03 AM](https://user-images.githubusercontent.com/12841220/64595273-436b6400-d3ba-11e9-87c5-4c3992b9a732.png)

**Comment by DannyDainton** [comment]
I see that you're using Node 12, Newman currently have issues with certain aspects of that version.

Are you able to give it a try with Node 10, just want to rule that out. You could use the node version manager, flip between the different versions.

https://github.com/nvm-sh/nvm/blob/master/README.md

The error message from Newman is a little confusing as it doesn't really tell you the actual reason why the reporter wasn't loaded. 

https://github.com/postmanlabs/newman/issues/1969

There is a open PR on that repo to fix this but there is also a work around in the comments of this issue. 

It's kinda hard to know what's going on for you here, the rate at which the reporter currently gets downloaded, if it was an issue for everyone, I would have lots of folks telling me the same thing - That's why I'm leaning towards it being environmental rather than the reporter. 

The only other thing that you could try is using it with a project and running the command from a script. There are lots of examples of this in the repo for this.

**Comment by JamalMSaad** [comment]
I fixed the issue by removing node completely and install it again then execute 'brew doctor' and  'brew cleanup' , then install newman and htmlextra reporter

Thank you for the help!

**Comment by DaveJuel** [comment]
> Not really sure what's going on here, I would have to put this down to an environmental issue as if I were a global problem for everyone, we would have more reports of the same issue.
> 
> I hate to give you a kinda turn on and off again solution but could you do the following:
> 
> `npm uninstall -g newman newman-reporter-htmlextra`
> 
> and then do a full install again:
> 
> `npm install -g newman newman-reporter-htmlextra`
> 
> By doing this, at least you know that both packages are installed at the same level before running the command again.

That's how it got fixed on my end.
