### ISSUE TITLE
Is it possible to show number of success, failed and skipped request instead of number of success, failed and skipped assertion?

### ISSUE THREAD

**Issue by 4nif** [DannyDainton/newman-reporter-htmlextra#163]
Hello @DannyDainton 

Is it possible to show number of success, failed and skipped request instead of number of success, failed and skipped assertion?

Currently default template show number of tests/assertion

thanks

**Comment by DannyDainton** [comment]
Can you give me an example of what that looks like, please?

What do you mean by a skipped request? How is that shown in the app?

The passed, failed and skipped all relate to the tests run within a request so that's why those are displayed in the summary table and in the individual requests.

**Comment by 4nif** [comment]
Hi @DannyDainton  I have collection structure as follow

![image](https://user-images.githubusercontent.com/31293565/71388955-18391780-262d-11ea-8dd4-d759bca332dc.png)

After we run through newman command line, htmlextra generate report like below
![image](https://user-images.githubusercontent.com/31293565/71389593-91d20500-262f-11ea-9b4f-9642543bd44c.png)

So instead of show number of `Total Assestions` pass, `Total Failed Tests` and `Total Skipped Tests`, is it possible to show `Total Passed Tests (number of request not pm.test)`, `Total Failed Tests (number of failed request not failed pm.test), and `Total Skipped Tests (number of skipped request)`.
So based on above scenario, the dashboard will show `1` for each (because i have 3 request only)

Thanks

**Comment by DannyDainton** [comment]
If you have a request without any assertions (tests) - How do you know if that passed, failed or was skipped?

Not sure I follow you, where is the information coming from that drives that?

The summary table below that image will tell you the total number of requests and if a request went through ok or contained an some form of error. There is no notion of a skipped request, it either runs and is OK or it runs and it fails for what ever reason. 

What you're looking at is a template and it can be changed, by yourself, to show anything you like. You could even just create a new template to use with the reporter.

**Comment by DannyDainton** [comment]
Hey @4nif,

I would love to close this out, it's not really an issue with the reporter, more about the way the data from Newman is presented. The templates are completely customisable so that can be shown any way you would. 

As the default template is a generic one, I'm not going to be changing it for your context/to solve your issue as its going to be very specific for you.

Those panels that you referred to as only to do with the tests/assertions made inside the requests. The request information and the details about how many ran and if those ran without error, can be found in the table below the image you posted.
