### ISSUE TITLE
Dashboard mark as green when "NO TESTS FOR THIS REQUEST"

### ISSUE THREAD

**Issue by 4nif** [DannyDainton/newman-reporter-htmlextra#166]
I have condition where postman unable to parsing json response in tests tab due to path or url response with 404, but dashboard show request with `green` colour on Total Requests tab.

It seems false positive because no test are running for that particular request due to 
![image](https://user-images.githubusercontent.com/31293565/71888441-bcb17280-3172-11ea-88c2-e12f62186c1d.png)

I think its better to mark them as Skipped test (with yellow colour)

**Comment by DannyDainton** [comment]
I have a bug template where you can capture all the relevant details, under the heading provided so I can actually investigate the problem. Please use this when raising an issue.

**Comment by DannyDainton** [comment]
A `Skipped Test` is a specific action done in the Postman UI using the `pm.test.skip` function. That action tells Newman that a particular test has been marked as `Skipped`. This is then reported out to the reporter. 

What you're suggesting is something different and has nothing to do with the actual action of skipping a test.

In your scenario, there was nothing wrong with the request, so it's marked as Green because it returned a `HTTP Status Code`, it was only going to the wrong URL so it caused the test that you added to fail and return the error you saw. A better approach would be to code against that situation and include tests that will give you the correct information.

**Comment by 4nif** [comment]
I got it. Thanks @DannyDainton
