### ISSUE TITLE
newman-reporter-htmlextra is not generate html file

### ISSUE THREAD

**Issue by Pradeep07-max** [DannyDainton/newman-reporter-htmlextra#187]
**Describe The Problem**
Newman generates the file with the size of  ZERO ,instead of html  extension.

**Steps To Reproduce**
Steps to reproduce the behaviour:
 -Run the CLI  >> newman run RegisterCompany.json -d companyjsonforregistration.json -n 16 -e MyWorkspace.postman_globals.json -r htmlextra --reporter-htmlextra-title "Registration Company API Test Reoprt" 

**What Are You Seeing**

-its generated the empty file instead of html report.

**Collection and Environment Files**

**Version and Platform Information:**
 - Postman v7.19.1
 - `newman` Version 4.5.5
 - `newman-reporter-htmlextra` Package Version [1.12.1]
- OS [Windows 10]
 - node -v [ v10.16.3]
  -npm -v : 6.9.0

**Additional Context**

1. if i use this CLI its working fine. but i need to run with title also ,

cmd >> newman run RegisterCompany.json -d companyjsonforregistration.json -n 16 -e MyWorkspace.postman_globals.json -r htmlextra --reporter-htmlextra-export example1.html

*i want attach my custom titile also is any possibility please let me know*
*working CLI*

**Comment by DannyDainton** [comment]
Could you tell me the Collection Name, please? Does it save the file in the `/newman` directory?

Could you also update the Newman version that you have, please.

**Comment by Pradeep07-max** [comment]
@DannyDainton this is my collection "RegisterCompany.json".
yes my file save in the /newman directory
![image](https://user-images.githubusercontent.com/62075895/76515598-db3c2e80-647f-11ea-8c9b-ae44ff08baa2.png)

 *Title flag is not working*

**Comment by DannyDainton** [comment]
The `title` would be shown on the front _summary_ page of the final report so you wouldn't see that in the filename. 

So in the Postman UI - Your collection is called "Working with data files"? Is this from a template?

What should be happening, is Newman would run the collection and the reporter would create a default filename in the format like this `Postman Echo-2020-03-11-13-51-59-266-0.html`.

Have you tried running the command with `-r cli,htmlextra` so you can see the output in the terminal, just so you know that it's running something.

**Comment by Pradeep07-max** [comment]
@DannyDainton , 
 i update the newman version.
yes Postman UI  also showing same name [ RegisterCompany.json ]

 cmd >> newman run RegisterCompany.json -r cli,htmlextra  
 - still getting same error.

**Comment by Pradeep07-max** [comment]
@DannyDainton ,

- my collection name is RegisterCompany.json.
- if check the json file its shows an "name": "Working with data files: ramen",  its  default value.this is the issue i thought.

  *Now its working 

i have want to use custom filename with tile in same CGI . is it possible .

*Thanks*

**Comment by DannyDainton** [comment]
> yes Postman UI also showing same name [ RegisterCompany.json ]

So your Collection in Postman, on the sidebar of the application is called `RegisterCompany.json` - As the default filename picks up the name of the collection from the UI and not the file you're using, I think you're mistaken.

> still getting same error.

What error? Are there any error messages? Did you see the cli output for your collection run in the command prompt?

I can't see what you have in front of you so you either need to provide images of everything that's going on in front of you or explain what you are seeing in much more detail. 

It's looking more like an environmental issue in your setup rather than something with the reporter as a lot of other people would have flagged this already because your use-case is quite basic.

Try this:

`npm uninstall -g newman newman-reporter-htmlextra`

`npm install -g newman newman-reporter-htmlextra`

`newman run RegisterCompany.json  -e MyWorkspace.postman_globals.json -r cli,htmlextra -d companyjsonforregistration.json -n 16 -reporter-htmlextra-title "Registration Company API Test Report"`

Upload an image of the console output after this.

**Comment by Pradeep07-max** [comment]
![image](https://user-images.githubusercontent.com/62075895/76519614-548b4f80-6487-11ea-9774-40efc125bbc3.png)

**Comment by DannyDainton** [comment]
So it works now?

**Comment by Pradeep07-max** [comment]
Thanks again @DannyDainton  for your support.  i have want to use custom filename with tile in same CGI . is it possible .

**Comment by DannyDainton** [comment]
I don't know what CGI means.

You can use multiple flags in the command - just add the `--reporter-htmlextra-export <filename.html>` to the command you have.

**Comment by Pradeep07-max** [comment]
this CLI is not working.
>> newman run RegisterCompany.json -r cli,htmlextra --reporter-htmlextra-title "Registration Company API Test Reoprt"-export RegCompany.html

**Comment by DannyDainton** [comment]
I can't help you if you tell me something isn't working and provide no further information.

What ever the command is you have just used - It's not the same as the one I posted. You have proved that the report works, remove the CLI from the list of reporters.
