### ISSUE TITLE
Add handlebars-helpers to count the number of folders, especially folders with failed tests

### ISSUE THREAD

**Issue by dami3nC** [DannyDainton/newman-reporter-htmlextra#191]
At first I would to thanks you for your project. I love work with it.

**Is your feature request related to a problem? Please describe.**
When I made postman collection I organize my tests into folders, but I can't have this indicators in my html report.

**Describe the solution you'd like**
I want to add an handlebars helper to have the number of folders with failed tests
If you want I can make a PR, but for now I don't right to create a new branch.

**Describe alternatives you've considered**
I can used the aggregations.length for the sum of my tests, but I can't count the number of folders with failed tests. 
So I clone your project and I add this handlebars helper and package it to use in my continous integration pipeline.

```javascript
    // Sums the total of folders with failed tests
    handlebars.registerHelper('totalFailedFolders', function (aggregations) {
        let failedFolders = 0;
        aggregations.forEach(aggregation => {
            aggregation.executions.forEach(execution => {
                if (execution.cumulativeTests.failed > 0) {
                    failedFolders++;
                }
            });
        });
        return failedFolders;
    });
```

**Additional context**
I organize my postman collection with folders because, when I want to test a feature I need to call several API and be sure than my api workflow work fine. For example if I want to test the creation of a customer, I need to test at least 2 call API, the first to create the customer and a second to check I can get this newly customer like I just created.

**Comment by DannyDainton** [comment]
Hey @dami3nC,

Would you be able to update the request with a before and after screenshot please, mask any sensitive data. It will just give me more context into what you're trying to do.

The helper can be added but I don't think I'll be updating any of the generic templates so you would need to use a custom template but it sounds like you're already doing that on your fork. :)

**Comment by dami3nC** [comment]
Hello @DannyDainton, 

Thanks for your quickly comment, effectively I don't need any update in the generic template, I made my custom one. 

**For more context:**
- Screenshot for total requests
<img width="420" alt="total" src="https://user-images.githubusercontent.com/18484511/78333586-62b22480-758a-11ea-86aa-6986f73f8159.png">
- Screenshot for test information (failed one)
<img width="384" alt="test-information" src="https://user-images.githubusercontent.com/18484511/78333590-6645ab80-758a-11ea-9003-ebf302544063.png">
- Screenshot for summary (before):
![before_summary](https://user-images.githubusercontent.com/18484511/78333989-36e36e80-758b-11ea-8b17-a19862a19743.png)
- Screenshot for summary (after with default template):
![after_summary_default-template](https://user-images.githubusercontent.com/18484511/78334020-4793e480-758b-11ea-995f-2fd92ac89a49.png)
- Screenshot for summary (after with custom template):
![after_summary_custom-template](https://user-images.githubusercontent.com/18484511/78334040-4f538900-758b-11ea-886b-2841a312ec0d.png)

**Comment by DannyDainton** [comment]
Looks cool - so you're displaying the number of tests rather than the number of assertions?

If you don't mind sharing the custom template, I would love to see what's going on 😁

I'll add the helper in, as soon as I get some time. I did try it out locally and it looked good to me but I need to have another look before pushed forward.

**Comment by dami3nC** [comment]
Yes, it's what I need, because for functional view, the number of assertions is not most important things, you want to know, how many features are ok. 

I haven't finished yet to customize the template, but I can share it with you. 
Do you want I join my draft in this comment?

**Comment by DannyDainton** [comment]
Yeah, it would be great to see how you're getting on so far. I love that you've created a custom template and using that for your context. The generic template are simply a way to allow folks to create reports out of the box and they really won't cover every single context and that's where having the ability to create and use your own comes in.

The underlying data from Newman is always going to be the same, there isn't a lot of logic going on to change it. Displaying that in a more meaningful way is key to seeing what you need, rather than me tell you what you should be seeing. :)

**Comment by dami3nC** [comment]
I join my draft custom template.
[html.zip](https://github.com/DannyDainton/newman-reporter-htmlextra/files/4426127/html.zip)

To use it I add this 2 helpers:
```javascript
    // Sums the total folders
    handlebars.registerHelper('totalFolders', function (aggregations) {
        return aggregations.length;
    });
    // Sums the total failed folders
    handlebars.registerHelper('totalFailedFolders', function (aggregations) {
        let failedFolders = 0;
        aggregations.forEach(aggregation => {
            aggregation.executions.forEach(execution => {
                if (execution.cumulativeTests.failed > 0) {
                    failedFolders++;
                }
            });
        });
        return failedFolders;
    });
```
It isn't needed to add the first one, I can use directly {{aggregations.length}} in my custom template.

**Comment by DannyDainton** [comment]
I'm finding it quite difficult to understand what you're doing in the template.

Are `Tests` in this context `Requests`? 

![Screenshot 2020-04-03 at 15 56 10](https://user-images.githubusercontent.com/17089546/78374715-d290d100-75c3-11ea-8ecb-781db051ef47.png)

I have a basic collection which has 2 requests, these are not in a folder. Each request has 3 tests and all of these failed because the Status Code is `200`.

```
pm.test("Status code is 201", function () {
    pm.response.to.have.status(201);
});

pm.test("Status code is 202", function () {
    pm.response.to.have.status(202);
});

pm.test("Status code is 203", function () {
    pm.response.to.have.status(203);
});
```

In the table above, it shows 6 assertions which is correct given the `pm.response` lines above, x2. This shows failed 50% though - To me, they all failed so 100% of them did.

**Comment by DannyDainton** [comment]
I've added the helpers to v1.13.0

**Comment by dami3nC** [comment]
Thanks you so much for this integration. For I now I don't have enough time to finish the customisation of the report. I'll send you as soon as I finish this, with postman collection for use it.
