### ISSUE TITLE
[Feature Request] Display variables on the final report when adding these via the CLI

### ISSUE THREAD

**Issue by karlOS123testing** [DannyDainton/newman-reporter-htmlextra#225]
I want to display in the report environment variables when I use the command:
 `newman run myCollection.json --env-var "var1=MyTest"`

**Describe the solution you'd like**
Variables should display in the "FILE INFORMATION" section as when we use a file with ENV variables:
`newman run myCollection.json -e myEnv.json`

**Comment by DannyDainton** [comment]
Hey @karlOS123testing,

Thanks for submitting this request, can you give me a little more information about your use case here?

How do you envisage this being displayed on the final report?

We need to be careful here because some users will use the `--env-var` flag to add variables that they don't want to store in the environments, like secrets for example. If you wanted to have a go and try to add that change yourself, PRs are always. welcome. 😄

**Comment by DannyDainton** [comment]
This _can_ be done. I quickly had a look at this with a combination of adding an environment file with `-e file.json` and `--env-var` from the command line.

<img width="1249" alt="Screenshot 2020-05-19 at 14 44 51" src="https://user-images.githubusercontent.com/17089546/82334200-908ae580-99df-11ea-9513-b8f9997cec83.png">

**Comment by DannyDainton** [comment]
I've basically done this locally and also added the ability to `hide` any variables that you don't want in the final report.

I'm still trying to tweak the design a little bit so it's not a huge change the to UI and maybe something that's hidden until folks want to see it.

I'll have a look tomorrow and add some tests etc before pushing forward.

**Comment by DannyDainton** [comment]
I think I'm going to settle on this for now and then change if anyone else has feedback, I can change it.

Users will also be able to use `--reporter-htmlextra-skipEnvironmentVars var1,var2` to hide the variable(s) from the final report.

![Environment_Values](https://user-images.githubusercontent.com/17089546/82426183-71dc2b80-9a7f-11ea-9c2a-fe27bc33b9bf.gif)
