### ISSUE TITLE
Ability to set the time zone that is used in report filenames.

### ISSUE THREAD

**Issue by fg78nc** [DannyDainton/newman-reporter-htmlextra#239]
**Is your feature request related to a problem? Please describe.**
Whenever I generate a report, the filename of the report contains the time that is different from my actual run time and time that is specified within the report itself.

**Describe the solution you'd like**
Ability to define your time zone or otherwise have a consist time between time portion in a file name and within the report itself

**Describe alternatives you've considered**
Nothing much, other than manually change the time (or write a script to do so)

**Additional context**
None.

**Comment by DannyDainton** [comment]
Hey @fg78nc 

This is something that has been mentioned before so I probably need to rethink my usage of the `helper-moment` module for that. I was only really using it so I could change the format of the time.

It's used in the template like this:

`<h5 class="text-center">{{moment date format="dddd, DD MMMM YYYY HH:mm:ss"}}</h5>`

You could change it to use the time coming from Newman instead:

<h5 class="text-center">{{timestamp}}</h5>

I'll have a think about how I can improve this in the reports.

**Comment by DannyDainton** [comment]
I've been exploring and expirementing with `moment-timezone` and I have something working that I might publish tomorrow and gauge the reaction.

**Comment by DannyDainton** [comment]
I've reread what your issue is again and I'm thinking about something different 😞 - The report display time does need to change so at least I've done that too 😄 

That time for the default filename comes from Newman, my reporter appends the Collection name to it but I don't set the timestamp.

Depending on how you're running the Newman command, you could use the the `--reporter-htmlextra-export` flag and create it with its own value that you can control a bit more `{Collection Name}_{timestamp}.html`

**Comment by DannyDainton** [comment]
I'm going to close this issue as the only real solution that I can offer is using the `export` flag and creating a filename with the time included.

I've published a new version of the reporter that should match TZs in the time inside the report now but if not, you can specify a location using the `timezone` flag and the string that is recognised by the `moment-timezone` module.
