### ISSUE TITLE
Headers - show/hide button (collapsed by default)

### ISSUE THREAD

**Issue by BubuFS** [DannyDainton/newman-reporter-htmlextra#252]
I'm aware there is an option to omit headers from reports, but it would be more convenient if they are included but simply collapsed by default, as they can get distracting most of the time.

**Comment by DannyDainton** [comment]
This seems very specific to the way that you, in your own context want the report. 

My suggestion would be to create a template and make the changes that you require. 

The default template is here:

https://github.com/DannyDainton/newman-reporter-htmlextra/blob/master/lib/dashboard-template.hbs

This isn't something that I'm going to be doing in the reporter so closing this issue.

**Comment by DannyDainton** [comment]
@BubuFS 

There you go - https://gist.github.com/DannyDainton/42e9124fcfc89bc2cbae772dc8668810

**Comment by BubuFS** [comment]
Hi Danny, I had completely overlooked the template feature and its obvious potential. Also, thanks a lot for putting together an example just for me ;-)

**Comment by DannyDainton** [comment]
That example doesn't have the additional changes like, folder description and folders run, like in the latest vertion but I'll add that in later.

The reporter template has been made to be generic so it caters for the masses rather than individual needs/preferences - it would be an absolute mess if that was the case 😁

That's where templates come in and I've seen people use all sorts of templates and created something that is specific to thier context.

**Comment by BubuFS** [comment]
Hi Danny, I have a technical question. In the template https://gist.github.com/DannyDainton/42e9124fcfc89bc2cbae772dc8668810#file-collapsedheaders-hbs-L905 I am trying to add {{cursor.ref}} in the "Request Headers" section, to make #id's unique, but it is not resolving, because of the {{#with request}}. How to I access the correct scope?  Works fine in "Response headers".

**Comment by BubuFS** [comment]
Replying to myself... used {{../cursor.ref}} to get parent context

**Comment by DannyDainton** [comment]
Glad I could help.... 😜
