### ISSUE TITLE
[Feature Request] Need to show request and response for failed scripts

### ISSUE THREAD

**Issue by apsys** [DannyDainton/newman-reporter-htmlextra#256]
**Is your feature request related to a problem? Please describe.**
Newman Run Dashboard doesn't show Request and Response for failed test scripts.

**Describe the solution you'd like**
Similar to Total Request that shows complete request and response it should also show for failed tests. It's easy to create a bug or report to stakeholders.

**Describe alternatives you've considered**
![Newman Summary Report 2020-08-14 15-30-01(1)](https://user-images.githubusercontent.com/13171750/90297475-72e4e500-de43-11ea-8d8d-a25f052e3d55.png)

**Additional context**

**Comment by DannyDainton** [comment]
Hey @apsys

Could you give me an example of what you mean by failed test script please?

An actual assertion failure or a legit JS failure.

If you could give me a scaled down collection with an example that would be easier to see what you mean and what data is coming from Newman in those scenarios.

I only have that data to play with so if it's not coming through in the summary then I can't show it on the final report 😁

**Comment by DannyDainton** [comment]
Those failures you see in that image should be also shown in the individual requests too - wouldn't that have the request / response info you need?

**Comment by DannyDainton** [comment]
Hey @apsys 

In the `Total Requests`, if a request has a failed assertion, you will see that here:

<img width="863" alt="Screenshot 2020-08-15 at 07 22 24" src="https://user-images.githubusercontent.com/17089546/90306770-3909f200-dec8-11ea-9dc2-212b99ce6187.png">

If the request has a script issue, as in, the syntax was incorrect that would also be seen here:

<img width="864" alt="Screenshot 2020-08-15 at 07 22 50" src="https://user-images.githubusercontent.com/17089546/90306769-36a79800-dec8-11ea-9ef6-a575b476e65a.png">

One of the times that I can think that the request won't show the full request/response would bee if you have some code in the pre-request script that would impact the execution of the request. On that occasion, I would expect not to see the full details of the request.

Is this what you're happing to see or are you talking about displaying something else?

**Comment by apsys** [comment]
1. My test suite has 1100+ tests. It takes 3-4 mins to open a generated report.
2. Yes, Total Requests shows all failed and passed tests with all details. I expect similar details for assertion failed tests (request body, header, response etc). 
3. In my company, my test suite runs 3-4 times during the day. I'm generating report and send it to slack channel. If a developer wants to take a look at failed tests he would need instructions from QA as the test is created by him. Providing request details makes a job simple. He would simply copy the request details and verify by himself else QA will have to provide it.
Suggestions:
You may want to change the color of Total Requests. Green represents Passed tests. 
Add one more option as Passed tests similar to Failed tests.

**Comment by DannyDainton** [comment]
OK.

1. The report is a static, dynamically generated html file. The more data going into the the report will cause those performance issues. Using the `--reporter-htmlextra-noSyntaxHighlighting` flag will help but it will never make it super snappy and its doing quite a few things. 

2. The report is a template and you're free to create your own report containing what you need and run it with the reporter. 

Adding that detail to another tab is going to just replicate the data, that's why it's there in the individual requests, with all the request data. 

3. Why do you need to create a report with that much detail 3-4 times a day? Who is consuming all that information?  Do your devs not have access to the collections being run? 

Sounds like you just need a list of failures or a reduce amount of information rather than the whole thing. 

There is a `--reporter-htmlextra-showOnlyFails` flag which will create a report with only that 😂

Again, the power is in your hands and creating your own template comes in to play when you want to change labels, colours, data etc.

**Comment by DannyDainton** [comment]
In terms of this feature, it's not something that I'm going to add to the generic report as I don't think it adds values and would only solve your particular usecase. This can be achieved with a custom template. 

I'm going to close this out as it not going to be actively worked on.

**Comment by DannyDainton** [comment]
Here's a template that could be used - It has a change to the headers so that they are collapsed by default but you could modify it to change the different parts of the report you wanted.

https://gist.github.com/DannyDainton/42e9124fcfc89bc2cbae772dc8668810
