### ISSUE TITLE
[Feature Request] Add more detail into the failed request tab

### ISSUE THREAD

**Issue by DannyDainton** [DannyDainton/newman-reporter-htmlextra#267]
The failed request tab is lacking details about the request that failed. This is due the way it's getting the data from a specific place, the rich request information is not part of that data set.

Need to redesign the tab content to include more meaningful information.

I don't really want to just replicate the information from the total requests as that's where you should be getting that information from but maybe a subset would be useful.

**Comment by laxmadendi** [comment]
Also, can you please consider adding the response message after the assertion error message? We would like to see the full response message along with the assertion status.

**Comment by DannyDainton** [comment]
You can't just add references to any part of the report - understanding _where_ the data for `{{response.body}}` is coming from is key here.

There's a reason why I didn't add it in there in the first place, it's just not part of the `summary.run.failures` object.

Can you add an example of the message you see after the assertion please, it will save on me/anyone else guessing what you mean 😂

**Comment by laxmadendi** [comment]
In the "Failed Tests", at present we see the failed Iteration number and what assertion(s) failed. But as a user I want to see the response from the API so that I can understand why the request failed and the assertion failed. Even though the request/response can be found in the Total Requests (/Iterations), it will be convenient to access the request/response in the Failed Tests so that I don't have to find for the failed tests from the all the iterations. It will be good to see all the failed tests and the corresponding request/response under one option "Failed Tests"

![assertion-error1](https://user-images.githubusercontent.com/58267619/92347629-af041200-f09e-11ea-84b1-670ce48b60e9.png)

**Comment by DannyDainton** [comment]
I'm working on something locally to help add some more details in there but it's not as simple as just adding different bits of data to that section....or it would have been done already 😂

**Comment by praveendvd** [comment]
> In the "Failed Tests", at present we see the failed Iteration number and what assertion(s) failed. But as a user I want to see the response from the API so that I can understand why the request failed and the assertion failed. Even though the request/response can be found in the Total Requests (/Iterations), it will be convenient to access the request/response in the Failed Tests so that I don't have to find for the failed tests from the all the iterations. It will be good to see all the failed tests and the corresponding request/response under one option "Failed Tests"
> 
> ![assertion-error1](https://user-images.githubusercontent.com/58267619/92347629-af041200-f09e-11ea-84b1-670ce48b60e9.png)


![image](https://user-images.githubusercontent.com/45095911/103543937-5403ef80-4ec5-11eb-9873-59d888098516.png)

clicking this shows only requests that are failed , it will have all details of failed requests as you want

**Comment by DannyDainton** [comment]
I'm not going to be doing this, this issue is more about not having the data available to do anything with that tab.

Once the data is available from Newman we can look at this again but for now, I'm going to close this issue.
