### ISSUE TITLE
[Feature Request] Adding number of requests failure in a run

### ISSUE THREAD

**Issue by Avinash9969** [DannyDainton/newman-reporter-htmlextra#281]
**Is your feature request related to a problem? Please describe.**
Current Report talks about Total Requests And Failed Tests( Assertion failures but not requests)
For Example, I have 500 tests and 1500 Assertions overall and If 1200 Assertions fail then report says  
Total Requests 500 And Failed Tests 1200 but in actual 100 test cases passed and only 400 test cases failed.

**Describe the solution you'd like**
Can you make changes to the report which tasks about test cases failed  and also after drilling down show me how many assertions failed.

**Describe alternatives you've considered**
Not consisdered any

**Additional context**

**Comment by DannyDainton** [comment]
Hey @Avinash9969 ,

Could you show me some example images of the report where the information is incorrect please?

I'm getting confused over your use of Requests, Tests and Assertions - can you point to something in the report that shows those differences, so there's no confusion as to what you mean for each.

**Comment by Avinash9969** [comment]
IMAGE#1
![image](https://user-images.githubusercontent.com/7777891/97585448-290da300-1a1f-11eb-9550-558dd0014d42.png)

In the report, 
You can see that the Number of requests were **03** (Call them test cases)
And Failed tests (Assertion failures) are **04** (Call them test steps)

When we go to Total requests sections what we see is 1 test case passed and 2 test cases failed But This information is not available in numbers. 
****
 IMAGE#2
![image](https://user-images.githubusercontent.com/7777891/97585478-2f9c1a80-1a1f-11eb-807d-a86a943927bf.png)


Report talks about the Assertion failures but not test case failures. As QA I would want to see how many test cases were executed how many passed and how many failed. It would make things easy if that information is also available

**Comment by DannyDainton** [comment]
Thanks for responding - This was the reason why I want to get some clarity here.

The naming convention that you're using isn't what the different items are called. The `requests`  are not called test case because they are literally requests. That request can have no `tests` within it and not do any assertions based on the response - It would be wrong to call that a `Test Case`.

Assertions are not Test steps, they are assertions (`pm.expect()` statements) inside a Test `pm.test()`.

As per that report you attached:

In the Summary table, it shows the total number of requests and the total number failed:

![image](https://user-images.githubusercontent.com/17089546/97594898-0d90a100-19fb-11eb-9345-c77d403ec7e2.png)

You have 3 Requests
![image](https://user-images.githubusercontent.com/17089546/97593193-58a9b480-19f9-11eb-86e0-ab7e678b2163.png)

You have 6 Failed Tests:

![image](https://user-images.githubusercontent.com/17089546/97593389-8e4e9d80-19f9-11eb-9213-ae958a57bad2.png)

![image](https://user-images.githubusercontent.com/17089546/97593429-99a1c900-19f9-11eb-8cb5-ec1f229a2eb6.png)

![image](https://user-images.githubusercontent.com/17089546/97593560-b50cd400-19f9-11eb-963a-70e820c6155e.png)

Although the last one contained a "Passing" assertion - The Test that the assertion was within, failed because all the assertions didn't pass.

---

The report you see is litterally a template showing the data in one way, you're able to chop and change your view to suit your own needs and them just passed the new template location to the reporter `--reporter-htmlextra-template <path>`.

If the label/text on a certain part isn't quite working for you, in your context, you have full control to change this.

**Comment by Avinash9969** [comment]
Hello @DannyDainton ,

My bad for not putting it in right way. Hope below example explains what I want to say.

languages Used **Java**
Library Used **TestNG**

Below is TestNG softAssertion example:

`package softassert.sample;

import org.testng.Assert;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

public class SoftAssertTest {

	@Test
	public void softAssertExample1() {
		SoftAssert softAssertion = new SoftAssert();
		System.out.println("SoftAssert Example 1 Was Started");
		softAssertion.assertTrue(false,"Assertion Example1");/// Assert#1
		softAssertion.assertTrue(false,"Assertion Example2");/// Assert#2
		System.out.println("SoftAssert Example 1 Was ended");
		softAssertion.assertAll();
		
	}

	@Test
	public void softAssertExample2() {
		SoftAssert softAssertion2 = new SoftAssert();
		System.out.println("SoftAssert Example 2 Was Started");
		softAssertion2.assertTrue(false, "Assertion Example3");/// Assert#3
		System.out.println("SoftAssert Example 2 Was ended");
		softAssertion2.assertAll();
	}
}
`

when we Execute code using TestNG , We get below logs
![image](https://user-images.githubusercontent.com/7777891/97601729-7f371200-1a30-11eb-8dec-fd205043f813.png)
![image](https://user-images.githubusercontent.com/7777891/97601777-8c540100-1a30-11eb-994e-390428d61c60.png)

Below is the execution status:
It says **run:2 and failures: 2**  even after we have **03** assertions mentioned in the script.
I was hoping for something of this sort in the html report. Which talks not only about the assertions failures but test case failures.
![image](https://user-images.githubusercontent.com/7777891/97600959-a0e3c980-1a2f-11eb-9154-687b45152e79.png)

Thanks

**Comment by DannyDainton** [comment]
That's not Postman, Newman or the reporter - not really sure how that's relevant in this context. :D

**Comment by Avinash9969** [comment]
@DannyDainton  It is actually all about testing and reporting.

**Comment by DannyDainton** [comment]
The way that a different language and a different reporter represents the data.

**Comment by Avinash9969** [comment]
Closing this Issue and the library provides a customization option as well.
