### ISSUE TITLE
[Feature Request] Improve standard of Failed Tests tab

### ISSUE THREAD

**Issue by lflucasferreira** [DannyDainton/newman-reporter-htmlextra#300]
##  **PROBLEM**

I realized that in the **Failed Tests** tab all failures are shown differently from the **Total Requests** tab. Let me point it out:

- The error type is shown in the scenario title, not good.

```
Iteration 1 - AssertionError - {Folder Name} - {Request Name}
```

![2021-01-19_151135](https://user-images.githubusercontent.com/5920654/105075616-bf72c300-5a68-11eb-89bd-de0b391ea9be.png)

## **SOLUTION**
Maybe the removal of **AssertionError** and **Folder Name** from the title would be better. The assertion error type can be seen when expanding the failure.

```
Iteration 1 - {Request Name}
```

![2021-01-19_151428](https://user-images.githubusercontent.com/5920654/105075832-0cef3000-5a69-11eb-990d-ed72cc2bfa7b.png)

## **ALTERNATIVES**
You could move the folder name to the main group of failures, as in the **Total Requests** tab. Grouping failed requests by folder path. The actual appearance leaves all failures by itself without giving us where we can find that request in our folders.

![2021-01-19_151003](https://user-images.githubusercontent.com/5920654/105075618-c00b5980-5a68-11eb-8a04-e087f177ab63.png)

**Comment by DannyDainton** [comment]
PRs are always welcome 😉

That tab came before the failure details were shown in the individual request view. It's also source from a different data set coming from Newman so the details are lacking due to there being not a lot to add there.

Feel free to tweak anything around and raise a PR for that, I can take a look. It's just a template so anything can be added, changed or removed from it.

**Comment by DannyDainton** [comment]
I'm not going to be doing this, feel free to raise a PR with the change if you feel its something you'd like to see.
