### ISSUE TITLE
<No matching version found for snyk-gradle-plugin@3.12.1>

### ISSUE THREAD

**Issue by arechavarria** [DannyDainton/newman-reporter-htmlextra#305]
The following error occurs with a synk package update

740 verbose node v12.19.0
741 verbose npm  v6.14.8
742 error code ETARGET
743 error notarget No matching version found for snyk-gradle-plugin@3.12.1.
744 error notarget In most cases you or one of your dependencies are requesting
744 error notarget a package version that doesn't exist.
744 error notarget
744 error notarget It was specified as a dependency of 'snyk'
745 verbose exit [ 1, true ]

**Comment by DannyDainton** [comment]
Without more details about what you're doing and maybe some images of where you see this - This is pretty meaningless.

As you opened a Bug, you would have seen this text in the template:

---



**What Are You Seeing**

A high-level description explaining the issue that you're facing. 

**Steps To Reproduce The Issue**

**Screenshots and Gifs**
I'm a visual person so it would be a HUGE help if you shared a screenshot of what you're seeing....
_A picture paints a thousand words..._

**Collection and Environment Files**

Any files that would allow me to reproduce the issue locally...

**Version and Platform Information:**
 - `newman` version 
 - `newman-reporter-htmlextra` version
 - OS 
 - The CLI command you've used to start Newman

**Additional Context**

Any contextual information that might relate to the problem?

---

I added this template so that people know what kind of information that I would need, to have at least an idea about an issue someone is seeing. You choose to delete this so now I need to ask more clarifying questions.
