### ISSUE TITLE
Security Vulnerabilities in dependencies autolinker/highlight.js

### ISSUE THREAD

**Issue by spawnms** [DannyDainton/newman-reporter-htmlextra#345]
We have a Scanner findings:
highlight.js: WS-2020-0208
autolinker: WS-2017-3770 | WS-2019-0540

Can you please update to the latest Version?

Thanks

**Comment by DannyDainton** [comment]
Updated some of the dependencies and we can reopen this issue if you feel there are still vulnerabilities.

**Comment by aberhallo** [comment]
Hi,

we still have a findings in our Whitesource scan for autolinker-0.28.1 (same CVEs as mentioned above). 

![image](https://user-images.githubusercontent.com/29666652/158957972-68abc3bf-d78d-4822-9dc9-fc7d24984489.png)

It seems handlebars-helpers is the problem since it is not maintained anymore (?).

Any idea?

Thanks
