### ISSUE TITLE
File Size of generated report

### ISSUE THREAD

**Issue by thetreythomas** [DannyDainton/newman-reporter-htmlextra#37]
I have a collection of 10 API calls. There is one test that runs at the Collection level, which is just making sure the API returns a 200. So 10 tests total.

One iteration of this collection generates a file that is ~1.4MB.

Ten iterations of this collection generates a file that is ~14MB.

We were going to kick this collection off tomorrow and do a stress test over the weekend, having it run 50,000 iterations. Based on the the file sizes above, that might make a ~50GB .html file.

What do you think?

I'm thinking there is most likely a limit, maybe even call it a "Best Practice", of iterations of logging everything before you only start logging failures.

I started messing around with the ELK stack...
https://www.elastic.co/
...I wonder how difficult it would be to get newman logging to logstash, and then use one of the Kibana boards to see all sorts of things from the data.

logstash supports all the below methods on bringing in data:
https://www.elastic.co/guide/en/logstash/current/input-plugins.html

**Comment by DannyDainton** [comment]
For the usecase that you're running and the output you need, I don't think this reporter or any html reporter is going to give you that. 

I would absolutely advise against kicking that off with this reporter listed. Just seems like it would be a waste of time in the end. 

As you mentioned kibana...have you looked at the `statsd` newman reporter? That would, with some tweeking, plot that on kibana or Grafana etc. 

https://www.npmjs.com/package/newman-reporter-statsd

Failing that, this tool is awesome and worth checking out:

https://artillery.io

**Comment by thetreythomas** [comment]
Sweet! Thanks for the quick reply and those suggestions.

We did NOT kick that off, wanted to ask you about it before we did it.

So is your report generator targeted to maybe 20 iterations max? What did you test up to, or recommend not to exceed?

For a 1 iteration test, I've already presented an .html report to my boss, and he absolutely loved the format. Time to start adding more tests. This is for sure a new tool that will get used for one off reports. Excellent work on this!

**Comment by DannyDainton** [comment]
So all the data that's displayed on the reports that you see is coming from Newman - The report output is _just_ a template. You can use the default one or you could create your own one to suit your needs. The data behind it will always be the same.

There are a number of different reporters out there, some created by Postman and some, like mine, that have been created as side projects. 

Take a look at NPM to see the different ones on there, they all need to follow this naming convention to work with Newman so they are quite easy to find `newman-reporter-<name>` :)

As for my reporter - I've seen users running reports with 5000 iterations and that was ok. The tabs on the reports are currently truncating when they get to around 21 so that in term makes the report look ugly - I'm open to PRs if you want to fix that :) I just don't have time to focus on the reporter right now.

I guess my questions would be around the value a full report, for every request, on every iteration is going to give people when you're running 500+ (That's an adjustable number) - If it was me who was receiving a report like that, I would read it all, I would want to know totals or big number values to make a snap assessment - If I needed to drill down into the data I could but I probably wouldn't check them all :)

**Comment by DannyDainton** [comment]
Not really sure what I can do about this particular problem - The other reporter and the Artillery tool are great things to look at, if you're doing a stress/load test with that many iterations. I'm not sure it a HTML reporter is going to provide you with that answers you need and it would be an epic file size.

You could take a look at the Newman project and see about creating a new reporter based on your requirements and the way you want to present the data.

**Comment by thetreythomas** [comment]
Danny, yeah I understand, no worries.

I understand things better now. You're right, these HTML reports aren't meant for large data sets.

I'll be using your HTML reporter for 1-5 iterations, and then I'm trying to get artillery to send everything to logstash for stress testing. If that doesn't get what is needed, I'll for sure drop you an email about making my own reporter.

Thanks for all your help, and pointing me to these other options.
