### ISSUE TITLE
newman: "htmlextra" reporter could not be loaded.

### ISSUE THREAD

**Issue by Sjain01** [DannyDainton/newman-reporter-htmlextra#38]
Hi I am using following versions :- 
 newman :- 4.1.0
newman-reporter-htmlextra - 1.6.10

Even though both the above applications are installed globally both on my local machine and jenkins server - I keep on getting following error :- 

```
newman: "htmlextra" reporter could not be loaded.
  please install reporter using npm
```
using following command to run the collection :-
`newman run "$collectionfilepath" -e "$environmentfilepath" --insecure --disable-unicode --reporters cli,junit,htmlextra --reporter-junit-export "$SourceFilePath/newman/myreport.xml" --reporter-htmlextra-export "$SourceFilePath/newman/myreport.html"`
Please advise how can i resolve this.

**Comment by DannyDainton** [comment]
This is an environment issue rather than a reporter issue. Have you tried uninstalling Newman and the reporters and reinstalling them. It needs to be at the same level as Newman so I suspect as much as you think it might be, I don't believe that it currently is. 

I don't know how you have set everything up so it would be difficult for me to know how to _solve_ this problem.

**Comment by DannyDainton** [comment]
I'm closing this issue for now, i don't think it's an problem with the reporter and its more on the environment side.

I will happily open again if it turns out it is the reporter and put a fix in place but for now I'm going to close it.
