### ISSUE TITLE
suggest show failed case full path include folder name

### ISSUE THREAD

**Issue by lleheaven** [DannyDainton/newman-reporter-htmlextra#43]
The report is great!

I just suggest the failed case title could add full folder path name, because my case is in different sub folders, when it fails, it only show the case name, but not show in which sub folder, then I need switch to "total Requests" tab to find the case, and the folder name always show gray color, 

I suggest that if in some sub folder have error case, it could show red color then you can quickly find your failed case. 
and on "total Requests" tab, if it have one button could unfolder is more better for search failed case. 

Thanks!

**Comment by DannyDainton** [comment]
All vaild suggestions, I'm open to PRs if you wanted to help achieve that or you could create a template to do those things rather than using the default output report.

**Comment by lleheaven** [comment]
the hoped foldername show like this : https://drive.google.com/open?id=1WjqEnVhkR77Rl81pSFMTrfJMBd2hhAlE

**Comment by DannyDainton** [comment]
That looks like the template from here:

https://github.com/MarcosEllys/awesome-newman-html-template

As that's just a template on top of the standard Postman HTML reporter, you could replicate what's been done there and use it with this reporter.

**Comment by DannyDainton** [comment]
Hey @lleheaven 

For the time being, I've included the full folder path on the `Failed Tests` tab.

<img width="1168" alt="Screenshot 2019-05-08 at 11 21 23" src="https://user-images.githubusercontent.com/17089546/57369146-ccf8f400-7184-11e9-83af-baf4b380305e.png">

Not really decided what I want to do about the `Total Requests` view yet - I was looking at added some sort of indication to the tab to show if any of the requests in the folder has `failed` tests, rather than display red everywhere.

<img width="1189" alt="Screenshot 2019-05-08 at 07 53 05" src="https://user-images.githubusercontent.com/17089546/57369287-13e6e980-7185-11e9-8639-935e651f9975.png">

There is the `--reporter-htmlextra-showOnlyFails` CLI flag, if you wanted to use it, to show only the fails in the `Total Tests` tab. It would be easier to find what you're looking for. :)

<img width="795" alt="Failed_Requests_View" src="https://user-images.githubusercontent.com/17089546/57369462-81931580-7185-11e9-9504-6cecbd9f2260.PNG">

**Comment by DannyDainton** [comment]
I'm going to close this issue for now and added something to the project board for additional changes.

**Comment by lleheaven** [comment]
Thanks Danny ! It is a great report !
